services:
  postgres:
    image: postgres:16-alpine
    container_name: authservice-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: mukhlis
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mukhlis -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
